# Use root/example as user/password credentials
version: '3.1'

services:
  db:
    image: mysql
    container_name: speechConverterDB
    restart: always
    environment:
      # MYSQL_ROOT_PASSWORD: example
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
    ports:
      - 5432:3306
